theme: jekyll-theme-cayman

title: My Portfolio
description: Welcome to my portfolio website!

# Navigation
include:
  - _includes/navigation.md

# Custom Styling
include:
  - assets/css/style.css

markdown: kramdown


